[advisories]
ignore = [
    "RUSTSEC-2025-0141", # bincode (via syntect)
    "RUSTSEC-2024-0436", # paste (via ratatui -> tui-textarea)
    "RUSTSEC-2024-0320", # yaml-rust (via syntect)
    "RUSTSEC-2026-0002"  # lru (via ratatui -> tui-textarea)
]
